logo = "img/LegendaryBanner.png"

jobs_OpenMenu = {
    -- "judge",
    "police",
    "ambulance",
    "cardealer",
    "cardealer2",
    "doj",
    "gebrauchtwagenhaendler",
    "fib",
    "mechanic",
    "mechanic2",
    "offambulance",
    "offordnungsamt",
    "offpolice",
    "offsheriff",
    "ordnungsamt",
    "sheriff",
    "unemployed",
    "unicorn",
}
jobs_SaveTemplate = {
    "police",
    "ambulance",
    "cardealer",
    "cardealer2",
    "doj",
    "gebrauchtwagenhaendler",
    "fib",
    "mechanic",
    "mechanic2",
    "offambulance",
    "offordnungsamt",
    "offpolice",
    "offsheriff",
    "ordnungsamt",
    "sheriff",
    "unemployed",
    "unicorn",
}
jobs_CreateDocument = {
    "police",
    "ambulance",
    "cardealer",
    "cardealer2",
    "doj",
    "gebrauchtwagenhaendler",
    "fib",
    "mechanic",
    "mechanic2",
    "offambulance",
    "offordnungsamt",
    "offpolice",
    "offsheriff",
    "ordnungsamt",
    "sheriff",
    "unemployed",
    "unicorn",
    "ambulance",
}
jobs_DeleteDocument = {
    "police",
    "ambulance",
    "cardealer",
    "cardealer2",
    "doj",
    "gebrauchtwagenhaendler",
    "fib",
    "mechanic",
    "mechanic2",
    "offambulance",
    "offordnungsamt",
    "offpolice",
    "offsheriff",
    "ordnungsamt",
    "sheriff",
    "unemployed",
    "unicorn",
}
jobs_CloseDocument = {
    "police",
    "ambulance",
    "cardealer",
    "cardealer2",
    "doj",
    "gebrauchtwagenhaendler",
    "fib",
    "mechanic",
    "mechanic2",
    "offambulance",
    "offordnungsamt",
    "offpolice",
    "offsheriff",
    "ordnungsamt",
    "sheriff",
    "unemployed",
    "unicorn",
}
jobs_CopyDocument = {
    "police",
    "ambulance",
    "cardealer",
    "cardealer2",
    "doj",
    "gebrauchtwagenhaendler",
    "fib",
    "mechanic",
    "mechanic2",
    "offambulance",
    "offordnungsamt",
    "offpolice",
    "offsheriff",
    "ordnungsamt",
    "sheriff",
    "unemployed",
    "unicorn",
}

commands = {
    documentmenu = "dokumente",
}

translate = {
    TR_TITLE            = "Dokumente",
    TR_EXIT             = "Schließen",
    TR_CREATE           = "Erstellen",
    TR_SAVE             = "Speichern",
    TR_CANCEL           = "Abbrechen",
    TR_ADD              = "+ Signatur",
    TR_REMOVE           = "- Signatur",
    TR_INSERT           = "Bild einfügen",
    TR_BUTTON_INSERT    = "EINFÜGEN",
    TR_EXAMPLE_NAME     = "Beispiel Name",
    TR_EXAMPLE_INFO     = "Beispiel Info",

    TR_LOADING          = "Lade...",
    TR_LOADING2         = "Warte...",
    TR_VIEW_MODELS      = "Vorlagen",
    TR_VIEW_MODELS2     = "Zeige Vorlagen",
    TR_VIEW_DOCUMENTS   = "Dokumente",
    TR_VIEW_DOCUMENTS2  = "Zeige deine Dokumente",
    TR_CREATE2          = "Erstelle neue Vorlage",
    TR_CREATE3          = "Erstelle neues Dokument",
    TR_CREATE4          = "Name des Dokuments?",
    TR_BACK             = "Zurück",
    TR_BACK2            = "Zurück zum Hauptmenü",
    TR_BACK3            = "Zurück zu Vorlagen",
    TR_BACK4            = "Zurück zum Hauptmenü",
    TR_BACK5            = "Zurück zu Dokumente",
    TR_EDIT             = "Bearbeiten",
    TR_EDIT2            = "Bearbeite Vorlage ",
    TR_EDIT3            = "Bearbeite Dokument ",
    TR_DELETE           = "Löschen",
    TR_DELETE2          = "Lösche Vorlage ",
    TR_DELETE3          = "Lösche Dokument ",
    TR_CLOSE            = "Schließe",
    TR_CLOSE2           = "Schließe Dokument ",
    TR_OPEN             = "Öffne",
    TR_OPEN2            = "Öffne Dokument ",
    TR_COPY             = "Kopie",
    TR_COPY2            = "Erstelle Kopie ",
    TR_COPY3            = '(Kopie) ',
    TR_GIVE             = "Geben",
    TR_GIVE2            = "Gebe Dokument weiter ",

    TR_NOT_PERMISSION = "Keine Berechtigung dafür!",
    TR_CREATED_DOCUMENT = "Dokument erstellt.",
    TR_UPDATED_DOCUMENT = "Dokument geupdated.",
    TR_CREATED_TEMPLATE = "Vorlage erstellt.",
    TR_UPDATED_TEMPLATE = "Vorlage geupdated.",
    TR_CLOSED_DOCUMENT = "Dokument geschlossen.",
    TR_GIVE_DOCUMENT = "Dokument überreicht.",
    TR_COPIED_DOCUMENT = "Kopie erstellt.",
    TR_DELETED_DOCUMENT = "Dokument gelöscht.",

}