Strings = {
    -- blips
    ["purchasable_house"] = "Kaufbares Haus",
    ["owned_house"] = "Dein Haus",
    ["access_house"] = "Haustür Schlüssel",
    ["purchased_house"] = "Verkauftes Haus",

    ["purchasable_apartment"] = "Kaufbares Apartment",
    ["owned_apartment"] = "Dein Apartment",
    ["access_apartment"] = "Apartment Schlüssel",
    ["purchased_apartment"] = "Verkauftes Apartment",

    ["ikea"] = "Möbelladen",
    ["robbery"] = "Raubüberfall",

    -- text for buttons
    ["buy_house"] = "Drücke ~INPUT_CONTEXT~ zum Kaufen ~b~%s~s~ für ~g~$%s~s~.",
    ["contact_rsa"] = "Drücke ~INPUT_CONTEXT~ zur Vorschau %s [#%s]",
    ["enter"] = "~INPUT_CONTEXT~ zum ~g~Betreten~w~ deines Hauses.",
    ["door"] = "Drücke ~INPUT_CONTEXT~ zum Öffnen der Optionen. Tür: (%s)",
    ["enter_ikea"] = "Drücke ~INPUT_CONTEXT~ zum ~g~Betreten.~w~\nDrücke   ~INPUT_DETONATE~zum ~r~Verkaufen.",
    ["furnishing"] = "Item: %s\nGeschwindigkeit: %s ~INPUT_COVER~ ~INPUT_TALK~\nDrücke ~INPUT_WEAPON_WHEEL_PREV~ ~INPUT_WEAPON_WHEEL_NEXT~ um Möbel zu Bewegen\nDrücke ~INPUT_ATTACK~ ~INPUT_AIM~ zum Drehen des Objekts\nDrücke ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ ~INPUT_CELLPHONE_UP~ ~INPUT_CELLPHONE_DOWN~ um das Objekt zu bewegen\nDrücke ~INPUT_DETONATE~ u, das Objekt zu dir zu teleportieren\nDrücke ~INPUT_FRONTEND_RDOWN~ zum Bestätigen\nDrücke ~INPUT_FRONTEND_RRIGHT~ zum abbrechen.",
    ["access_storage"] = "Drücke ~INPUT_DETONATE~ zum Benutzen des Lagers.",
    ["press_manage"] = "\n\n~INPUT_DETONATE~ um das Haus zu ~p~verwalten~w~.",
    ["enter_garage"] = "Drücke ~INPUT_CONTEXT~ zum Betreten der Garage.",
    ["store_garage"] = "Drücke ~INPUT_CONTEXT~ zum Einparken deines Autos.",
    ["breach_door"] = "\nDrücke ~INPUT_DETONATE~ Zum Aufbrechen der Tür.",
    ["lockpick_door"] = "\n\n~INPUT_DETONATE~ zum ~r~Knacken~w~ der Tür.",
    ["pole_dance"] = "Drücke ~INPUT_CONTEXT~ um den Pole Dance zu Starten",
    ["stop_dancing"] = "Drücke ~INPUT_VEH_DUCK~ um das Tanzen zu Stoppen",
    ["lap_dance"] = "Drücke ~INPUT_CONTEXT~ um lapdance zu starten\nDrücke   ~INPUT_VEH_EXIT~zum sitzen",
    ["storage_wardrobe"] = "Lager oder Kleiderschrank",
    ["storage_option"] = "Öffne Lager",
    ["wardrobe_option"] = "Öffne Kleiderschrank",
    ["select_outfit"] = "Wähle dein Outfit",
    ["lockpicking"] = "Wenn das Schloss sich verlangsamt , bist du nahe an der richtigen Position\nLockpicks Übrig: %s\n\nBenutze ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ um das Schloss zu drehen\n~INPUT_FRONTEND_RDOWN~ Aufschließen\n~INPUT_FRONTEND_RRIGHT~Abbrechen",

    -- ikea
    ["viewing_furniture"] = "Durchsuchen ~r~%s~s~.\n ~INPUT_REPLAY_BACK~ ~INPUT_REPLAY_ADVANCE~ zum Durchstöbern.\n ~INPUT_REPLAY_FFWD~ ~INPUT_REPLAY_REWIND~ um Kategorie zu wechseln.\n ~INPUT_MOVE_LEFT_ONLY~ ~INPUT_MOVE_RIGHT_ONLY~ zum Rotieren.\n ~INPUT_MOVE_UP_ONLY~ ~INPUT_MOVE_DOWN_ONLY~ zum Zoomen.%s\n ~INPUT_FRONTEND_RDOWN~ zum Kaufen ~b~%s~s~ für ~g~$%s~s~.\n ~INPUT_FRONTEND_RRIGHT~ zum Verlassen",
    ["confirm_purchase"] = "Drücke ~b~%s~s~ zum ~g~$%s~s~?\n\n~INPUT_FRONTEND_RDOWN~ Kaufen\n~INPUT_FRONTEND_RRIGHT~ Abbrechen",
    ["purchased"] = "Gekauft %s für ~g~$%s~s~.",
    ["storage"] = "\n  | ~g~Ermöglicht das Einlagern~w~  |",

    -- locked state
    ["locked"] = "Verschlossen",
    ["unlocked"] = "Aufgeschlossen",
    
    -- text for menus 
    ["house_key"] = "Haustür Schlüssel",
    ["door_menu"] = "Tür Menü",
    ["toggle_lock"] = "Aufschließen / Abschließen",
    ["exit"] = "Verlassen",
    ["furnish"] = "Einrichten",
    ["put_furniture"] = "Möbelstück Platzieren",
    ["manage_furniture"] = "Möbel verwalten",
    ["amount_furniture"] = "x%s %s",
    ["confirm_house_purchase"] = "Kaufe %s für <span style='color:lime'>$%s</span>",
    ["are_you_sure"] = "Kaufen %s?",
    ["what_interior"] = "Welchen Innenraum wählst du ?",
    ["interior_number"] = "Innenraum #%s",
    ["remove_furniture"] = "Wegschmeißen %s?",
    ["inventory"] = "Lager",
    ["inventory_weapons"] = "Lager für - Waffen",
    ["inventory_items"] = "Lager für - Gegenstände",
    ["black_money"] = "Schwarzgeld: <span style='color:red'>$%s</span>",
    ["cash"] = "Bargeld: <span style='color:lime'>$%s</span>",
    ["put"] = "Einlagern",
    ["get"] = "Auslagern",
    ["deposit"] = "Einlagern",
    ["withdraw"] = "Auslagern",
    ["weapons"] = "Waffen",
    ["items"] = "Gegenstände",
    ["amount_of"] = "Anzahl von %s?",
    ["make_key_copy"] = "Mache eine Kopie deines Schlüssels",
    ["resell_house"] = "Dieses Haus verkaufen Für <span style='color:lime'>$%s</span>",
    ["kick_someone_out"] = "Person Rausschmeißen",
    ["kick_out?"] = "Rausschmeißen %s?",
    ["kick_out"] = "Rausschmeißen %s",
    ["preview"] = "Vorschau verfügbarer Innenräume",
    ["previewing"] = "~h~Haus Besichtigung\n\n~h~~s~Wenn du das Haus kaufst , wird einer dieser Inneräume dein Eigenheim\nInnenraum %s von %s Inneräumen\n~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ zum Anzeigen ~b~anderer Inneräume~w~\n~INPUT_FRONTEND_RRIGHT~ um die Besichtigung zu ~r~beenden~w~.",
    ["previewing_nohelp"] = "~h~Vorzeige Haus~h~\nKontaktiere einen Immobilienmarkler um dieses Haus zu Kaufen.\n~INPUT_FRONTEND_RRIGHT~ um die Besichtigung zu beenden.",
    ["transfer_house"] = "Haus Übergeben",
    ["transfer_property"] = "Eigentum übergeben an %s?",
    ["none_nearby"] = "Niemand ist in deiner Nähe",
    ["yes"] = "Ja",
    ["no"] = "Nein",

    -- text for notifications
    ["no_spawn"] = "Ich konnte Keinen verfügbaren Ort für dein Haus / Apartment finden.\n\nWende dich an die Projektleitung um mehr Häuser hinzuzufügen.",
    ["error_locked"] = "Ich konnte das Haus / Apartment nicht betreten - Die Tür ist verschlossen.",
    ["not_near_door"] = "Du bist nicht in der nähe einer Tür , aufgrund dessen kannst du sie weder Aufschließen noch Verschließen.",
    ["must_be_number"] = "Du musst eine Nummer eingeben.",
    ["dont_have"] = "Soviel besitzt du nicht.",
    ["not_enough"] = "Soviel ist nicht in diesem Lager verfügbar",
    ["cant_carry"] = "Soviel kannst du nicht tragen", 
    ["has_items"] = "Dieses Objekt hat noch Items Gelagert , aufgrund dessen kannst du es nicht entfernen!",
    ["someone_in_house_cant_sell"] = "Es ist noch jemand im haus - aufgrund dessen kannst du es nicht verkaufen !",
    ["cant_own_more"] = "Du kannst nicht noch mehr Häuser besitzen.",
    ["no_lockpicks"] = "Du hast keine Dietriche.",
    ["robbery_progress"] = "ACHTUNG!! Jemand bricht in dein Haus ein ! Guck auf dein GPS!",
    ["you_got_kicked"] = "Du wurdest aus dem haus Geworfen.",
    ["house_spawned_transfer"] = "Jemand ist im Haus, du kannst dieses nicht Übergeben.",
    ["nolonger_nearby"] = "Der Spieler ist nichtmehr in deiner Nähe",
    ["nearby_storage"] = "Jemand ist in deiner Nähe , deshalb kannst du das Lager nicht benutzen.",
    ["locked_door"] = "Du hast die Tür abgeschlossen",
    ["unlocked_door"] = "Du hast die Tür aufgeschlossen",
    -- text for loading
    ["purchasing"] = "Kaufen",
    ["removing_furniture"] = "Möbelstück Entfernen",
    ["loading_object"] = "Lade Objekt",
    ["loading_storage"] = "Lade Lager",
    ["buy_house"] = "Drücke ~INPUT_CONTEXT~ um eine ~p~Haus Besichtigung~w~ vorzunehmen",

    
    -- other
    ["rotation"] = "Rotation: %s",
    ["not_enough_cops"] = "Es sind nicht genug Polizisten online!",
}